POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "My First Blog",
  "author": "Viktor",
  "url": "https://example.com",
  "likes": 5,
  "userId": "67e69a7eb588c6c26586663c"
}