DELETE http://localhost:3001/api/blogs/67e6d68289fcbea4d785862e
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvbWFuIiwiaWQiOiI2N2U2OWE3ZWI1ODhjNmMyNjU4NjY2M2MiLCJpYXQiOjE3NDM1MDc2MjQsImV4cCI6MTc0MzUxMTIyNH0.jbmaq2FINLSHuIi1p-p3BKcs-lnMmFnQT3GyAmzPAv4
