DELETE http://localhost:3001/api/blogs/67ec026fe59bcd731911f08f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvbWFuIiwiaWQiOiI2N2U2OWE3ZWI1ODhjNmMyNjU4NjY2M2MiLCJpYXQiOjE3NDM1MTkyMTcsImV4cCI6MTc0MzUyMjgxN30.-ZyxlgT1YB3yV8jyk_r899nS3tgkcH3eF3MwKBIFUSI
